version: '{build}'
max_jobs: 1
image: Visual Studio 2017
# We only need the latest
shallow_clone: true
branches:
  only:
  - master

environment:
  # Github token to commit pushed packages to repository
  GITHUB_USERNAME: pdk-bot
  GITHUB_TOKEN:
    secure: IUjB8ctqO2KSF954odTdyODM+hc3Rdr1gmXzaD1sy/XODBALJ7TrQe3j5UdIqE2I #https://ci.appveyor.com/tools/encrypt

install:
- ps: |
    "Build info"
    '  {0,-20} {1}' -f 'SCHEDULED BUILD:', ($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true')
    '  {0,-20} {1}' -f 'FORCED BUILD:'   , ($Env:APPVEYOR_FORCED_BUILD    -eq 'true')
    '  {0,-20} {1}' -f 'RE BUILD:'       , ($Env:APPVEYOR_RE_BUILD        -eq 'true')
    '  {0,-20} {1}' -f 'GITHUB_TOKEN:'   , ($Env:GITHUB_TOKEN             -ne $null)

build_script:
- ps: |
    $ErrorActionPreference = 'Continue'
    # Only trigger if the GTIHUB_TOKEN exists
    # Only trigger the project sync on a forced or scheduled build, NOT per PR.
    if ( ($null -ne $ENV:GITHUB_TOKEN) -and (($Env:APPVEYOR_SCHEDULED_BUILD -eq 'true') -or ($Env:APPVEYOR_FORCED_BUILD -eq 'true')) ) {
      .\tools\SyncProjects.ps1
    }
